### ISSUE TITLE
[BUG] Customizing the UI breaks formatting

### ISSUE THREAD

**Issue by pat-s** [UdelaRInterior/ansible-role-jitsi-meet#21]
When setting `jitsi_meet_customize_the_ui: true` the site looks as follows

<img width="717" alt="image" src="https://user-images.githubusercontent.com/8430564/82602246-13af6580-9bb1-11ea-8d06-11fffca56ebe.png">

While nothing changes in the app, accessing the jitsi-server via a browser looks awful. Is this an upstream bug?

**Comment by santiagomr** [comment]
How do you have setted the other variables related to UI customization? Everything by default?

Particularly, the result that you observe seems to be related to bad CSS. Be aware of the warning explained [in the code](https://github.com/UdelaRInterior/ansible-role-jitsi-meet/blob/3c52ffe8ed0ed3907e9e85c4667c93f3d4873df6/defaults/main.yml#L245):
```yaml
# By default it is an empty string because the CSS file is a bundled file for
# the entire site, and it change very frequently with each release. It will be
# replaced only if you have a custom CSS file and indicate its path in this variable
jitsi_meet_css_file: ''
```

**Comment by pat-s** [comment]
> How do you have setted the other variables related to UI customization? Everything by default?

yes

I have not set `jitsi_meet_css_file` and therefore I assumed that the default upstream CSS is being used. However no CSS  at all seems to be applied in this case?

Or am I doing something wrong? Does it work for you? Didn't you test it lately when setting `jitsi_meet_customize_the_ui: true` in my recent issue?

**Comment by santiagomr** [comment]
Yes, I tried it. With `jitsi_meet_customize_the_ui: true` and the others vars at their default value, the result I get in both Firefox and Chrome is:

![imagen](https://user-images.githubusercontent.com/21184254/82672911-5f94f580-9c17-11ea-8da6-5fbe4f6a8902.png)

Anyway, keep in mind that:
> How do you have setted the other variables related to UI customization? Everything by default?
>
> yes

This is equivalent to not customizing anything  (`jitsi_meet_customize_the_ui: false`), since the default values are the same as those used by the Jitsi Meet vanilla installer.

I suspect that somewhere in your project [some of these variables](
https://github.com/UdelaRInterior/ansible-role-jitsi-meet/blob/3c52ffe8ed0ed3907e9e85c4667c93f3d4873df6/defaults/main.yml#L239) are being reassigned with an invalid value:

```yaml
jitsi_meet_lang: 'en'
jitsi_meet_appname: 'My app name'
jitsi_meet_org_link: 'https://link-to-my-organization.com'
jitsi_meet_welcomepage_title: 'Secure, fully featured, and completely free video conferencing'
jitsi_meet_welcomepage_description: 'Go ahead, video chat with the whole team. In fact, invite everyone you know. __app__ is a fully encrypted, 100% open source video conferencing solution that you can use all day, every day, for free — with no account needed.'
jitsi_meet_css_file: ''
jitsi_meet_welcome_page_additions_file: welcomePageAdditionalContent.html.j2
jitsi_meet_favicon_file: images/favicon.ico
jitsi_meet_logo_file: images/jitsilogo.png
jitsi_meet_watermark_file: images/watermark.png
jitsi_meet_default_background: '#474747'
jitsi_meet_show_video_background: true
jitsi_meet_default_remote_display_name: 'Fellow Jitster'
jitsi_meet_default_local_display_name: 'me'
jitsi_meet_generate_roomnames_on_welcome_page: true
jitsi_meet_lang_detection: false
```

For the error you have, in addition to the CSS, I recommend you check the template you are using in `jitsi_meet_welcome_page_additions_file` and look for errors in the console of developer tools of your web browsers
